version: '3.8'

services:
  steam-bot:
    build: .
    container_name: steam-discord-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - STEAM_WEB_API_KEY=${STEAM_WEB_API_KEY}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - steam-bot-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  steam-bot-network:
    driver: bridge

volumes:
  bot-data:
    driver: local
