# ZarinAI - Docker Compose для Google Cloud VM
version: '3.8'

services:
  zarinai-bot:
    build: .
    container_name: zarinai_bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - ENVIRONMENT=production
    volumes:
      - ./steam_bot.db:/app/steam_bot.db
      - ./logs:/app/logs
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Nginx прокси (опционально)
  nginx:
    image: nginx:alpine
    container_name: zarinai_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - zarinai-bot
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

  # Watchtower для автообновлений (опционально)
  watchtower:
    image: containrrr/watchtower
    container_name: zarinai_watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600  # Проверка каждый час
      - WATCHTOWER_INCLUDE_STOPPED=true
    command: zarinai_bot
